image: alpine:latest

variables:
  BRANCH_NAME: $CI_COMMIT_REF_NAME

before_script:
  - apk add --no-cache doxygen
  - apk add --no-cache py3-pip
  - pip3 install sphinx-rtd-theme breathe sphinx-sitemap

pages:
  script:
    - apk add --no-cache git
    - git clone $CI_REPOSITORY_URL
    - cd hpc-img-convolution # Replace with the path to your repository
    - cd docs
    - make html
    - touch build/html/.nojekyll
    - mv build/html public/
  environment: production
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
